---
title: Southtowns Care Center
timezone: UTC
collections:
  bios:
    title: Bios
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: bios
  values:
    colors: ["red", "green", "blue"]
    layout: "project"
    map:
      latitude:
      longitude:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
